[package]
name = "steviegoodman/unnamed-project"
description = "No description provided."
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
Comm = "sleitnick/comm@1.0.1"